include:
  - artifact: keyball61_left
    board: nice_nano//zmk
    shield: keyball61_left nice_view_adapter nice_view
  - artifact: keyball61_right
    board: nice_nano//zmk
    shield: keyball61_right nice_view
    snippets:
      - studio-rpc-usb-uart
  - artifact: keyball61_reset
    board: nice_nano//zmk
    shield: settings_reset
