CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610=y
CONFIG_PM_DEVICE=n
CONFIG_PMW3610_REPORT_INTERVAL_MIN=8
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=200
CONFIG_PMW3610_INVERT_X=n
CONFIG_PMW3610_INVERT_Y=y

CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# DYA Studio and Runtime Input Settings
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=768

# Battery History Support
CONFIG_ZMK_BATTERY_HISTORY=y
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y
# 15 minutes timeout (15 * 60 * 1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

