manifest:
  version: 1.2
  defaults:
    remote: cormoran
    revision: main
  remotes:
    - name: cormoran
      url-base: https://github.com/cormoran
  projects:
    - name: zmk-west-commands
      import: true
    - name: zmk
      import:
        file: app/west.yml
      clone-depth: 1
      revision: v0.3-branch+dya
    - name: zephyr
      revision: v3.5.0+zmk-fixes+nrf-half-duplex-uart
      clone-depth: 1
      import:
        name-blocklist:
          - ci-tools
          - hal_altera
          - hal_cypress
          - hal_infineon
          - hal_microchip
          - hal_nxp
          - hal_openisa
          - hal_silabs
          - hal_xtensa
          - hal_st
          - hal_ti
          - loramac-node
          - mcuboot
          - mcumgr
          - net-tools
          - openthread
          - edtt
          - trusted-firmware-m
    - name: zmk-pmw3610-driver
    - name: zmk-feature-default-layer
      revision: zmk-v0.3.0.0
    - name: zmk-driver-animation
      revision: zmk-v0.3.0.0
    - name: zmk-driver-ext-power-transient
    - name: zmk-module-ble-management
      revision: zmk-v0.3.0.0
    - name: zmk-module-battery-history
    - name: zmk-module-runtime-input-processor
      revision: zmk-v0.3.0.0
    - name: zmk-behavior-runtime-sensor-rotate
    - name: zmk-module-settings-rpc
  self:
    path: config
